	var resceneicons = L.layerGroup().addTo(map);
	function RESceneOnOff() {
	var chbox;
	chbox=document.getElementById('RESceneButton');
	if (chbox.checked) {
/* RETriggerScene */
/* BB 1-11 =11 */
	icons = new L.marker([182729, 177101], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([130746, 153382], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-12561, 132708], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-22472, 153672], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-32543, 171846], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-54376, 191120], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([50224, 190902], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([83848, 198237], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([120767, 191553], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([157430, 183289], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([52114, 132483], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* DAB 1-4 6-7  =6 */
	icons = new L.marker([153227, 5183], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([194704, -5490], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([194995, 18360], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([185829, 161059], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([164688, 142401], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([85436, 75917], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* DB 1-2 4-5 8-12 14 16-18 24-25 =15 */
	icons = new L.marker([42547, -99367], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([25115, -79077], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([130903, 66239], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-119690, 22450], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([42323, -8763], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([119328, -67772], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([156918, -142487], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([182664, -139270], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([71437, -58288], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([186994, -152782], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-29978, -40372], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([174268, -109989], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([94612, -160488], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-70562, -43156], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([34352, -48570], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* DM 1 5 7 9 =4 */
	icons = new L.marker([-95658, -18687], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-59255, 49107], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-169025, -31726], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-125247, -9060], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* DWD 1-13 =13 */
	icons = new L.marker([-176983, -59917], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-169553, 72099], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([198168, 75167], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([191920, 97468], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-183028, 23875], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([160331, 43700], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([157191, 90832], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-71080, 13678], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-97355, 27898], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-16837, 108156], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-142061, 98577], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-122426, 55901], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([179548, 74723], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* JM 1-4 7-17 =15 */
	icons = new L.marker([-108604, 186395], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-102032, 178448], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-75920, 132733], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-74158, 152445], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-90735, 135255], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-107824, 129132], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-96709, 108840], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-58400, 155856], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-63399, 170675], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-107718, 166015], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-166063, 110607], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-169255, 169803], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-103746, 115679], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-116494, 148942], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-121562, 203845], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* OB 1 3 6-9 12-14 17-20 =13 */
	icons = new L.marker([-28069, -142310], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([16016, 144688], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([8240, -68968], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([116857, -6265], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([51512, -163600], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([121584, -167976], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([184736, -46952], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([43246, 31392], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([51199, 107128], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([9384, 96039], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-18268, -5799], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-25780, 66799], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-60367, -2067], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* TS 1-2 =2 */
	icons = new L.marker([-127655, 192459], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([36138, 10878], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
/* ZW 1 3-8 11 =8 */
	icons = new L.marker([-129831, -121800], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-142714, -86611], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-84822, -106091], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-105259, -115318], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-110031, -90452], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-108869, -75201], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-135652, -171505], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	icons = new L.marker([-94850, -146644], {icon: icon_random3}).addTo(resceneicons).bindPopup("Место случайной встречи (Scene)").bindTooltip("Место случайной встречи (Scene)", {direction: 'top'});
	}
	else {
		resceneicons.clearLayers();
	}
}